package org.fossasia.openevent.general.attendees.forms

object FormIdentifier {
    val FIRST_NAME = "firstname"
    val LAST_NAME = "lastname"
    val EMAIL = "email"
    val ADDRESS = "address"
    val CITY = "city"
    val STATE = "state"
    val COUNTRY = "country"
    val JOB_TITLE = "jobTitle"
    val PHONE = "phone"
    val TAX_INFO = "taxBusinessInfo"
    val BILLING_ADDRESS = "billingAddress"
    val HOME_ADDRESS = "homeAddress"
    val SHIPPING_ADDRESS = "shippingAddress"
    val COMPANY = "company"
    val WORK_ADDRESS = "workAddress"
    val WORK_PHONE = "workPhone"
    val WEBSITE = "website"
    val BLOG = "blog"
    val TWITTER = "twitter"
    val FACEBOOK = "facebook"
    val GITHUB = "github"
    val GENDER = "gender"
}
