import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions`
 */
object Libs {
    const val com_diffplug_gradle_spotless_gradle_plugin: String =
            "com.diffplug.gradle.spotless:com.diffplug.gradle.spotless.gradle.plugin:" +
            Versions.com_diffplug_gradle_spotless_gradle_plugin

    const val de_fayard_buildsrcversions_gradle_plugin: String =
            "de.fayard.buildSrcVersions:de.fayard.buildSrcVersions.gradle.plugin:" +
            Versions.de_fayard_buildsrcversions_gradle_plugin

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val navigation_safe_args_gradle_plugin: String =
            "android.arch.navigation:navigation-safe-args-gradle-plugin:" +
            Versions.navigation_safe_args_gradle_plugin

    /**
     * https://developer.android.com/studio
     */
    const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:" +
            Versions.com_android_tools_build_gradle

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val lifecycle_reactivestreams_ktx: String =
            "androidx.lifecycle:lifecycle-reactivestreams-ktx:" +
            Versions.lifecycle_reactivestreams_ktx

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val lifecycle_reactivestreams: String = "androidx.lifecycle:lifecycle-reactivestreams:" +
            Versions.lifecycle_reactivestreams

    /**
     * https://github.com/miteshpithadiya/SearchableSpinner
     */
    const val searchablespinnerlibrary: String =
            "com.toptoche.searchablespinner:searchablespinnerlibrary:" +
            Versions.searchablespinnerlibrary

    const val local_properties_plugin: String =
            "gradle.plugin.com.github.b3er.local.properties:local-properties-plugin:" +
            Versions.local_properties_plugin

    const val play_services_auth: String = "com.google.android.gms:play-services-auth:" +
            Versions.com_google_android_gms

    const val play_services_location: String = "com.google.android.gms:play-services-location:" +
            Versions.com_google_android_gms

    /**
     * https://github.com/square/retrofit/
     */
    const val adapter_rxjava2: String = "com.squareup.retrofit2:adapter-rxjava2:" +
            Versions.com_squareup_retrofit2

    /**
     * https://github.com/square/retrofit/
     */
    const val converter_jackson: String = "com.squareup.retrofit2:converter-jackson:" +
            Versions.com_squareup_retrofit2

    /**
     * https://github.com/square/retrofit/
     */
    const val retrofit: String = "com.squareup.retrofit2:retrofit:" +
            Versions.com_squareup_retrofit2

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val lifecycle_common_java8: String = "androidx.lifecycle:lifecycle-common-java8:" +
            Versions.lifecycle_common_java8

    const val zxing_android_embedded: String = "com.journeyapps:zxing-android-embedded:" +
            Versions.zxing_android_embedded

    /**
     * https://github.com/FasterXML/jackson-module-kotlin
     */
    const val jackson_module_kotlin: String =
            "com.fasterxml.jackson.module:jackson-module-kotlin:" + Versions.jackson_module_kotlin

    const val databinding_adapters: String = "androidx.databinding:databinding-adapters:" +
            Versions.androidx_databinding

    /**
     * https://developer.android.com/studio
     */
    const val databinding_common: String = "androidx.databinding:databinding-common:" +
            Versions.androidx_databinding

    /**
     * https://developer.android.com/studio
     */
    const val databinding_compiler: String = "androidx.databinding:databinding-compiler:" +
            Versions.androidx_databinding

    const val databinding_runtime: String = "androidx.databinding:databinding-runtime:" +
            Versions.androidx_databinding

    /**
     * https://developer.android.com/testing
     */
    const val androidx_test_runner: String = "androidx.test:runner:" + Versions.androidx_test_runner

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val lifecycle_extensions: String = "androidx.lifecycle:lifecycle-extensions:" +
            Versions.lifecycle_extensions

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_android_extensions: String =
            "org.jetbrains.kotlin:kotlin-android-extensions:" + Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_android_extensions_runtime: String =
            "org.jetbrains.kotlin:kotlin-android-extensions-runtime:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_annotation_processing_gradle: String =
            "org.jetbrains.kotlin:kotlin-annotation-processing-gradle:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_gradle_plugin: String = "org.jetbrains.kotlin:kotlin-gradle-plugin:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_stdlib_jdk7: String = "org.jetbrains.kotlin:kotlin-stdlib-jdk7:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val navigation_fragment_ktx: String = "androidx.navigation:navigation-fragment-ktx:" +
            Versions.androidx_navigation

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val navigation_ui_ktx: String = "androidx.navigation:navigation-ui-ktx:" +
            Versions.androidx_navigation

    /**
     * https://github.com/facebook/stetho
     */
    const val stetho: String = "com.facebook.stetho:stetho:" + Versions.com_facebook_stetho

    /**
     * https://github.com/facebook/stetho
     */
    const val stetho_okhttp3: String = "com.facebook.stetho:stetho-okhttp3:" +
            Versions.com_facebook_stetho

    /**
     * https://github.com/square/okhttp
     */
    const val logging_interceptor: String = "com.squareup.okhttp3:logging-interceptor:" +
            Versions.logging_interceptor

    /**
     * https://github.com/mapbox/mapbox-java
     */
    const val mapbox_sdk_services: String = "com.mapbox.mapboxsdk:mapbox-sdk-services:" +
            Versions.mapbox_sdk_services

    /**
     * https://github.com/Blogcat/Android-ExpandableTextView
     */
    const val expandabletextview: String = "at.blogc:expandabletextview:" +
            Versions.expandabletextview

    /**
     * http://github.com/square/leakcanary/
     */
    const val leakcanary_android: String = "com.squareup.leakcanary:leakcanary-android:" +
            Versions.leakcanary_android

    /**
     * https://github.com/JetBrains/anko
     */
    const val anko_commons: String = "org.jetbrains.anko:anko-commons:" +
            Versions.org_jetbrains_anko

    /**
     * https://github.com/JetBrains/anko
     */
    const val anko_design: String = "org.jetbrains.anko:anko-design:" + Versions.org_jetbrains_anko

    /**
     * scm:git@github.com:paypal/PayPal-Android-SDK.git
     */
    const val paypal_android_sdk: String = "com.paypal.sdk:paypal-android-sdk:" +
            Versions.paypal_android_sdk

    /**
     * https://github.com/jasminb/jsonapi-converter
     */
    const val jsonapi_converter: String = "com.github.jasminb:jsonapi-converter:" +
            Versions.jsonapi_converter

    /**
     * http://tools.android.com
     */
    const val constraintlayout: String = "androidx.constraintlayout:constraintlayout:" +
            Versions.constraintlayout

    const val expandablelayout: String = "net.cachapa.expandablelayout:expandablelayout:" +
            Versions.expandablelayout

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val paging_runtime: String = "androidx.paging:paging-runtime:" + Versions.androidx_paging

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val paging_rxjava2: String = "androidx.paging:paging-rxjava2:" + Versions.androidx_paging

    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val collection_ktx: String = "androidx.collection:collection-ktx:" +
            Versions.collection_ktx

    /**
     * https://github.com/IsseiAoki/SimpleCropView
     */
    const val simplecropview: String = "com.isseiaoki:simplecropview:" + Versions.simplecropview

    /**
     * https://github.com/stripe/stripe-android
     */
    const val stripe_android: String = "com.stripe:stripe-android:" + Versions.stripe_android

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val room_compiler: String = "androidx.room:room-compiler:" + Versions.androidx_room

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val room_runtime: String = "androidx.room:room-runtime:" + Versions.androidx_room

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val room_rxjava2: String = "androidx.room:room-rxjava2:" + Versions.androidx_room

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val room_testing: String = "androidx.room:room-testing:" + Versions.androidx_room

    /**
     * https://developer.android.com/testing
     */
    const val espresso_core: String = "androidx.test.espresso:espresso-core:" +
            Versions.espresso_core

    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val exifinterface: String = "androidx.exifinterface:exifinterface:" +
            Versions.exifinterface

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val core_testing: String = "androidx.arch.core:core-testing:" + Versions.core_testing

    /**
     * https://developer.android.com/jetpack/androidx
     */
    const val fragment_ktx: String = "androidx.fragment:fragment-ktx:" + Versions.fragment_ktx

    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val recyclerview: String = "androidx.recyclerview:recyclerview:" + Versions.recyclerview

    /**
     * https://developer.android.com/studio
     */
    const val lint_gradle: String = "com.android.tools.lint:lint-gradle:" + Versions.lint_gradle

    const val stetho_noop: String = "com.github.iamareebjamal:stetho-noop:" + Versions.stetho_noop

    /**
     * https://github.com/JakeWharton/ThreeTenABP/
     */
    const val threetenabp: String = "com.jakewharton.threetenabp:threetenabp:" +
            Versions.threetenabp

    /**
     * https://developer.android.com/jetpack/androidx
     */
    const val preference: String = "androidx.preference:preference:" + Versions.preference

    /**
     * https://www.threeten.org/threetenbp
     */
    const val threetenbp: String = "org.threeten:threetenbp:" + Versions.threetenbp

    /**
     * https://developer.android.com/jetpack/androidx
     */
    const val appcompat: String = "androidx.appcompat:appcompat:" + Versions.appcompat

    /**
     * https://github.com/ReactiveX/RxAndroid
     */
    const val rxandroid: String = "io.reactivex.rxjava2:rxandroid:" + Versions.rxandroid

    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val cardview: String = "androidx.cardview:cardview:" + Versions.cardview

    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val core_ktx: String = "androidx.core:core-ktx:" + Versions.core_ktx

    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val material: String = "com.google.android.material:material:" + Versions.material

    const val multidex: String = "androidx.multidex:multidex:" + Versions.multidex

    const val koin_android: String = "org.koin:koin-android:" + Versions.org_koin

    const val koin_androidx_scope: String = "org.koin:koin-androidx-scope:" + Versions.org_koin

    const val koin_androidx_viewmodel: String = "org.koin:koin-androidx-viewmodel:" +
            Versions.org_koin

    const val koin_test: String = "org.koin:koin-test:" + Versions.org_koin

    /**
     * https://github.com/ReactiveX/RxKotlin
     */
    const val rxkotlin: String = "io.reactivex.rxjava2:rxkotlin:" + Versions.rxkotlin

    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val browser: String = "androidx.browser:browser:" + Versions.browser

    /**
     * https://github.com/square/picasso/
     */
    const val picasso: String = "com.squareup.picasso:picasso:" + Versions.picasso

    /**
     * http://facebook.github.io/shimmer-android
     */
    const val shimmer: String = "com.facebook.shimmer:shimmer:" + Versions.shimmer

    /**
     * https://github.com/ReactiveX/RxJava
     */
    const val rxjava: String = "io.reactivex.rxjava2:rxjava:" + Versions.rxjava

    /**
     * https://github.com/JakeWharton/timber
     */
    const val timber: String = "com.jakewharton.timber:timber:" + Versions.timber

    /**
     * https://developer.android.com/studio
     */
    const val aapt2: String = "com.android.tools.build:aapt2:" + Versions.aapt2

    /**
     * http://junit.org
     */
    const val junit: String = "junit:junit:" + Versions.junit
}
