import kotlin.String
import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val com_diffplug_gradle_spotless_gradle_plugin: String = "3.24.2"

    const val de_fayard_buildsrcversions_gradle_plugin: String = "0.6.1"

    const val navigation_safe_args_gradle_plugin: String = "1.0.0"

    const val com_android_tools_build_gradle: String = "3.5.0"

    const val lifecycle_reactivestreams_ktx: String = "2.1.0"

    const val lifecycle_reactivestreams: String = "2.2.0-alpha04"

    const val searchablespinnerlibrary: String = "1.3.1"

    const val local_properties_plugin: String = "1.1"

    const val com_google_android_gms: String = "17.0.0"

    const val com_squareup_retrofit2: String = "2.6.1"

    const val lifecycle_common_java8: String = "2.2.0-alpha04"

    const val zxing_android_embedded: String = "3.6.0" // available: "4.0.2"

    const val jackson_module_kotlin: String = "2.9.6" // available: "2.9.9"

    const val androidx_databinding: String = "3.5.0"

    const val androidx_test_runner: String = "1.2.0"

    const val lifecycle_extensions: String = "2.2.0-alpha04"

    const val org_jetbrains_kotlin: String = "1.3.50"

    const val androidx_navigation: String = "2.1.0"

    const val com_facebook_stetho: String = "1.5.1"

    const val logging_interceptor: String = "4.2.0"

    const val mapbox_sdk_services: String = "4.8.0"

    const val expandabletextview: String = "1.0.5"

    const val leakcanary_android: String = "2.0-beta-3"

    const val org_jetbrains_anko: String = "0.10.8"

    const val paypal_android_sdk: String = "2.16.0"

    const val jsonapi_converter: String = "0.9"

    const val constraintlayout: String = "2.0.0-beta2"

    const val expandablelayout: String = "2.9.2"

    const val androidx_paging: String = "2.1.0"

    const val collection_ktx: String = "1.1.0"

    const val simplecropview: String = "1.1.8"

    const val stripe_android: String = "11.1.1" // available: "11.1.2"

    const val androidx_room: String = "2.1.0"

    const val espresso_core: String = "3.2.0"

    const val exifinterface: String = "1.0.0"

    const val core_testing: String = "2.1.0"

    const val fragment_ktx: String = "1.1.0"

    const val recyclerview: String = "1.1.0-beta04"

    const val lint_gradle: String = "26.5.0"

    const val stetho_noop: String = "1.2.1"

    const val threetenabp: String = "1.2.1"

    const val preference: String = "1.1.0"

    const val threetenbp: String = "1.4.0"

    const val appcompat: String = "1.1.0"

    const val rxandroid: String = "2.1.1"

    const val cardview: String = "1.0.0"

    const val core_ktx: String = "1.1.0"

    const val material: String = "1.1.0-alpha10"

    const val multidex: String = "2.0.1"

    const val org_koin: String = "2.0.1"

    const val rxkotlin: String = "2.4.0"

    const val browser: String = "1.0.0"

    const val picasso: String = "2.71828"

    const val shimmer: String = "0.5.0"

    const val rxjava: String = "2.2.12"

    const val timber: String = "4.7.1"

    const val aapt2: String = "3.5.0-5435860"

    const val junit: String = "4.12"

    /**
     * Current version: "5.4.1"
     * See issue 19: How to update Gradle itself?
     * https://github.com/jmfayard/buildSrcVersions/issues/19
     */
    const val gradleLatestVersion: String = "5.6.2"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
    inline get() =
            id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
